services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 5

  api_service:
    build:
      context: ./backend
      dockerfile: api_service/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"

  tcp_service:
    build:
      context: ./backend
      dockerfile: tcp_service/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api_service
    environment:
      - VITE_API_URL=http://api_service:8000

volumes:
  pgdata:
