# Blueprint for SEP4 monorepo: API, ML, TCP, Frontend, NATS, Postgres

services:
  # 1) FastAPI backend
  - name: api-service
    type: web
    runtime: docker
    plan: starter
    region: frankfurt
    branch: main
    autoDeployTrigger: off
    buildFilter:
      paths:
        - backend/api_service/**
    dockerContext: .
    dockerfilePath: backend/api_service/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pg
          property: connectionString
      - key: NATS_URL
        fromService:
          name: nats-server
          type: pserv
          property: hostport
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_MOCK_DATA
        value: "false"


  # 3) TCP listener for IoT → NATS
  - name: tcp-service
    type: pserv
    runtime: docker
    plan: starter
    region: frankfurt
    branch: main
    autoDeployTrigger: off
    buildFilter:
      paths:
        - backend/tcp_service/**
    dockerContext: .
    dockerfilePath: backend/tcp_service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pg
          property: connectionString
      - key: NATS_URL
        fromService:
          name: nats-server
          type: pserv
          property: hostport
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_MOCK_DATA
        value: "false"

  # 4) React/Vite frontend
  - name: frontend-service
    type: web
    runtime: docker
    plan: starter
    region: frankfurt
    branch: main
    autoDeployTrigger: off
    buildFilter:
      paths:
        - my-app/**
    dockerContext: .
    dockerfilePath: my-app/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: VITE_API_URL
        value: https://api-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_MOCK_DATA
        value: "false"

  # 5) NATS message broker
  - name: nats-server
    type: pserv
    runtime: image
    image:
      url: nats:2
    plan: starter
    region: frankfurt

databases:
  # 6) PostgreSQL
  - name: pg
    region: frankfurt
    plan: starter
    diskSizeGB: 10
    databaseName: appdb
    user: render_user
    ipAllowList: []
