name: Test API Service

on:
  pull_request:
    paths:           # run only when API files change
      - 'backend/api_service/**'
  push:
    branches: [ main ]
    paths:
      - 'backend/api_service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install prod + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/api_service/requirements.txt
          pip install -r backend/api_service/requirements-dev.txt

      - name: Run pytest
        run: pytest backend/api_service/tests -q
