name: Deploy Frontend Service

on:
  push:
    paths:
      - 'frontend/**'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Frontend to Render
        uses: render-examples/github-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceName: frontend-service
