name: Deploy Frontend Service

on:
  push:
    paths:
      - 'my-app/**'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Render CLI
        run: curl -fsSL https://cdn.render.com/cli/install.sh | bash

      - name: Deploy Frontend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          export PATH="$HOME/.render:$PATH"
          render services deploy frontend-service --yes --from-file render.yaml
