name: Deploy TCP Service

on:
  push:
    paths:
      - 'backend/tcp_service/**'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy TCP to Render
        uses: render-examples/github-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceName: tcp-service
