name: Deploy ML Service

on:
  push:
    paths:
      - 'backend/ml_service/**'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy ML to Render
        uses: render-examples/github-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceName: ml-service
