name: Deploy API Service

on:
  push:
    paths:
      - 'backend/api_service/**'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy API to Render
        uses: render-examples/github-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceName: api-service
