name: ML-CI

on:
  push:
    paths: ["ml/**"]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r ml/requirements.txt
      - run: pytest ml/tests -q
      - run: |
          cd ml && python -m src.train
          echo "MODEL_READY=yes" >> $GITHUB_ENV
      - name: Build & push container
        if: env.MODEL_READY == 'yes'
        uses: docker/build-push-action@v5
        with:
          context: ./ml
          push: true
          tags: ghcr.io/${{ github.repository }}/greenhouse-ml:${{ github.sha }}
